# Generated by Django 3.0.5 on 2021-06-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='review',
            name='review_discriprion',
            field=models.CharField(blank=True, help_text='Напишите отзыв', max_length=300, verbose_name='Описание отзыва'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_name',
            field=models.CharField(blank=True, help_text='Напишите тему отзыва', max_length=300, verbose_name='Тема отзыва'),
        ),
        migrations.AlterUniqueTogether(
            name='title',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unigue_category'),
        ),
    ]
