# Generated by Django 3.0.5 on 2021-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210605_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, help_text='Введите оценку от 1 до 10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_description',
            field=models.TextField(blank=True, help_text='Дайте краткое описание категории', verbose_name='Описание категории'),
        ),
    ]
