# Generated by Django 3.0.5 on 2021-06-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210605_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_description',
            field=models.TextField(blank=True, help_text='Дайте краткое описание категории', verbose_name='Описание категории'),
        ),
    ]
