# Generated by Django 3.0.5 on 2021-06-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210607_0120'),
        ('api', '0005_auto_20210606_1752'),
    ]

    operations = [
    ]
