# Generated by Django 3.0.5 on 2021-06-07 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210607_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2021, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
