# Generated by Django 3.0.5 on 2021-06-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210608_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2021, help_text='Напишите здесь год выпуска произведения', max_digits=4, verbose_name='Год выпуска'),
            preserve_default=False,
        ),
    ]
