# Generated by Django 3.0.5 on 2021-06-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210608_2351'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='titles',
            name='unigue_category',
        ),
    ]
