# Generated by Django 3.0.5 on 2021-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210609_0012'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='titles',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unigue_category'),
        ),
    ]
