# Generated by Django 3.0.5 on 2021-05-31 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Напишите название новой категории', max_length=50, verbose_name='Название категории')),
                ('category_description', models.TextField(help_text='Дайте краткое опишисание новой категории', verbose_name='Описание категории')),
            ],
            options={
                'ordering': ['-category_name'],
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(help_text='Напишите название нового жанра', max_length=50, verbose_name='Название жанра')),
                ('genre_description', models.TextField(help_text='Дайте краткое опишисание нового жанра', verbose_name='Описание жанра')),
            ],
            options={
                'ordering': ['-genre_name'],
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.TextField(help_text='Напишите здесь название нового произведения', verbose_name='Название произведения')),
                ('title_description', models.TextField(help_text='Напишите здесь название нового произведения', verbose_name='Описание произведения')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации произведения')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор произведения')),
                ('image', models.ImageField(blank=True, help_text='Вставьте изображение для своего произведения', null=True, upload_to='titles/')),
                ('category', models.ForeignKey(blank=True, help_text='Выберите категорию добавляемого произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='api.Categories', verbose_name='Категория произведения')),
                ('genre', models.ForeignKey(blank=True, help_text='Выберите жанр добавляемого произведения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titles', to='api.Genres', verbose_name='Жанр произведения')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='titles',
            constraint=models.UniqueConstraint(fields=('title_name', 'category'), name='unigue_category'),
        ),
    ]
